    public enum NodeType
    {
        None,
        MicrosoftKeyword,
        VisualKeyword,
        StudioKeyword,
        SolutionKeyword,
        FileKeyword,
        FormatKeyword,
        VersionKeyword,
        VisualStudioVersionKeyword,
        MinimumVisualStudioVersionKeyword,
        ProjectKeyword,
        EndProjectKeyword,
        GlobalKeyword,
        EndGlobalKeyword,
        GlobalSectionKeyword,
        EndGlobalSectionKeyword,
        PreSolutionKeyword,
        PostSolutionKeyword,
        SolutionConfigurationPlatformsKeyword,
        ProjectConfigurationPlatformsKeyword,
        SolutionPropertiesKeyword,
        NestedProjectsKeyword,
        ExtensibilityGlobalsKeyword,
        SolutionGuidKeyword,

        StringToken,
        NumberToken,
        VersionToken,

        DotToken,
        HashToken,
        CommaToken,
        EqualSignToken,
        OpenParenToken,
        CloseParenToken,
        OpenBraceToken,
        CloseBraceToken,
        KeyToken,
        ValueToken,


        TabToken,
        SpaceToken,
        NewLineToken,
        ByteOrderMarkToken,
        EndOfFileToken,
    }
